### ISSUE TITLE
大佬，请问您是如何添加数量如此庞大的网站接口的？

### ISSUE THREAD

**Issue by RussiaVk** [CreditTone/regchecker#2]
我在开发类似的项目，几个月累死累活才添加几十个（各式风控，太难了）。

**Comment by CreditTone** [comment]
诶，我也不好讲。可能你没找对方法



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: RussiaVk <notifications@github.com&gt;
发送时间: 2020年6月6日 14:03
收件人: CreditTone/regchecker <regchecker@noreply.github.com&gt;
抄送: Subscribed <subscribed@noreply.github.com&gt;
主题: 回复：[CreditTone/regchecker] 大佬，请问您是如何添加数量如此庞大的网站接口的？ (#2)





 
我在开发类似的项目，几个月累死累活才添加几十个（各式风控，太难了）。
